### PR TITLE
https with new packages

### PR DESCRIPTION
**Pull request by azban**
i was seeing some issues with the latests requests + urllib3, and passing through to https. i brought over the changes from https://github.com/gabrielfalcao/HTTPretty/pull/290, but was still having an issue because we weren't connecting sockets until real_sendall, which is too late for urllib3 + pyopenssl. i tried to pull in https://github.com/gabrielfalcao/HTTPretty/pull/302, but extracting pyopenssl from urllib3 breaks SNI and some other desirable features. i got around this by patching the pyopenssl package specifically if it is installed.

there is a slight limitation, but all of the tests passed, so it seems that given the current intended use case, it should be acceptable. in socket.connect and ssl_wrap_socket, we do not have access to anything but hostname and port, so i just tried to match on what we have. this means that if you are mocking out by method or query string, we will still try to connect a socket to that address. this seems like a reasonable limitation, but should probably be mentioned somewhere. otherwise, we will have to do some pretty weird monkey patching of the http libraries so that we can attach request information to the fake socket in order for it to be available when those functions are called.

### CODE REVIEW

**Comment by jamescarr** [comment]
This looks good... any reason we can't merge?

**Comment by appierys** [comment]
It would be great to see this merged~

File: httpretty/core.py [hunk 1]
```diff
@@ -508,8 +521,17 @@ def __getattr__(self, name):
             return getattr(self.truesock, name)
 
 
-def fake_wrap_socket(s, *args, **kw):
-    return s
+def fake_wrap_socket(orig_wrap_socket_fn, _socket, *args, **kw):
```
Comment (AdamWill) [inline httpretty/core.py]: I seem to run into a problem with this with requests/urllib3, because it calls `ssl_wrap_socket` like this:

        self.sock = ssl_wrap_socket(
            sock=conn,
            keyfile=self.key_file,
            certfile=self.cert_file,
            ssl_context=self.ssl_context,
        )

note it names the socket arg, as `sock` (which is what the original `ssl_wrap_socket` function, and python's `ssl.wrap_socket`, both call their socket argument). But because it doesn't have the same name in this fake function, I get an error that `fake_wrap_socket` didn't get enough arguments (because that `sock=` is just treated as part of `**kw`).

To fix it, just change `_socket` in this function's signature (and all the code, obviously) to `sock`.

File: tests/unit/test_passthrough.py [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+@httprettified
+def test_http_passthrough():
+    url = 'http://ip4.me/'
+    response1 = requests.get(url)
+
+    HTTPretty.enable()
+    HTTPretty.register_uri(HTTPretty.GET, 'http://google.com/', body="Not Google")
+
+    response2 = requests.get('http://google.com/')
+    expect(response2.content).to.equal('Not Google')
```
Comment (AdamWill) [inline tests/unit/test_passthrough.py]: This should be `b'Not Google'`, as the content of a requests `Response` is a bytestring. Python 2 considers `'Not Google'` and `b'Not Google'` to be equal, but Python 3 does not, so this test fails on Python 3.

File: tests/unit/test_passthrough.py [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+def test_https_passthrough():
+    url = 'https://www.cloudflare.com/ips-v4'
+
+    response1 = requests.get(url)
+
+    HTTPretty.enable()
+    HTTPretty.register_uri(HTTPretty.GET, 'http://google.com/', body="Not Google")
+
+    response2 = requests.get('http://google.com/')
+    expect(response2.content).to.equal('Not Google')
```
Comment (AdamWill) [inline tests/unit/test_passthrough.py]: Ditto here.

File: httpretty/core.py [hunk 4]
```diff
@@ -318,15 +325,21 @@ def connect(self, address):
                 self.is_http = self._port in ports_to_check
 
             if not self.is_http:
-                if self.truesock:
+                if self.truesock and not self._connected_truesock:
                     self.truesock.connect(self._address)
+                    self._connected_truesock = True
                 else:
                     raise UnmockedError()
+            elif self.truesock is not None and not self._connected_truesock:
```
Comment (AdamWill) [inline httpretty/core.py]: Note: this change makes the `test_fakesock_socket_getpeercert` test from `test_core.py` actually connect out to somewhere.com, whereas I believe it did not do so before.

File: tests/unit/test_passthrough.py [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
+# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
+# OTHER DEALINGS IN THE SOFTWARE.
+
+def test_http_passthrough():
+    from sure import expect
+    from httpretty import HTTPretty
+    import requests
+    
+    url = 'http://checkip.dyndns.com/'
```
Comment (AdamWill) [inline tests/unit/test_passthrough.py]: It would be nice if these tests didn't require a real remote roundtrip. There's some code in `test_bypass` for running a local HTTP server, though it doesn't handle HTTPS, I don't think.

File: tests/functional/test_requests.py [hunk 6]
```diff
@@ -938,6 +936,13 @@ def test_httpretty_should_allow_registering_regexes_with_port_and_give_a_proper_
     expect(HTTPretty.last_request.path).to.equal('/v1/deal;brand=gap?first_name=chuck&last_name=norris')
 
 
+@httprettified
+def test_httpretty_should_passthrough_for_ssl():
+    "HTTPretty should allow passthroughs for ssl"
+    response = requests.get('https://dev-app-1.picnichealth.com')
```
Comment (AdamWill) [inline tests/functional/test_requests.py]: again, it'd be good for this not to require a real remote trip.

File: httpretty/core.py [hunk 7]
```diff
@@ -99,17 +99,16 @@
     if not PY3:
         old_sslwrap_simple = ssl.sslwrap_simple
     old_sslsocket = ssl.SSLSocket
+    old_sslcontext = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
```
Comment (AdamWill) [inline httpretty/core.py]: This does not work with Python 2.6:

    AttributeError: 'module' object has no attribute 'SSLContext'

I don't know if we care about Python 2.6 compatibility, though.

File: httpretty/core.py [hunk 8]
```diff
@@ -937,6 +957,53 @@ def match_uriinfo(cls, info):
...
+    def match_https_hostname(cls, hostname):
+        items = sorted(
+            cls._entries.items(),
+            key=lambda matcher_entries: matcher_entries[0].priority,
+            reverse=True,
+        )
+        for matcher, value in items:
+            if matcher.info is None:
+                pattern_with_port = "https://{}:".format(hostname)
+                pattern_without_port = "https://{}/".format(hostname)
```
Comment (AdamWill) [inline httpretty/core.py]: These `{}` are unnecessarily Python 2.6-incompatible; it's pretty painless to just do `{0}` instead, and then it works with 2.6.

File: httpretty/core.py [hunk 9]
```diff
@@ -937,6 +957,53 @@ def match_uriinfo(cls, info):
...
+        for matcher, value in items:
+            if matcher.info is None:
+                if port in POTENTIAL_HTTPS_PORTS:
+                    scheme = 'https://'
+                else:
+                    scheme = 'http://'
+
+                pattern_without_port = "{}{}/".format(scheme, hostname)
+                pattern_with_port = "{}{}:{}/".format(scheme, hostname, port)
+                for pattern in [pattern_with_port, pattern_without_port]:
```
Comment (AdamWill) [inline httpretty/core.py]: ditto the note above. Here, you can do `{0}{1}` and `{0}{1}:{2}`.

File: tests/functional/test_requests.py [hunk 10]
```diff
@@ -567,7 +567,9 @@ def test_httpretty_provides_easy_access_to_querystrings_with_regexes():
     })
 
 
+from unittest import skip
```
Comment (AdamWill) [inline tests/functional/test_requests.py]: This doesn't work with Python 2.6, where `unittest` doesn't have `skip`. A possible workaround is to do this:

    try:
        from unittest import skip
    except ImportError:
        from unittest2 import skip

which will allow it to work with Python 2.6 if you install the `unittest2` library which provides a backport of the 2.7 unittest for earlier Pythons.

**Comment by AdamWill** [comment]
FWIW, http://pkgs.fedoraproject.org/cgit/rpms/python-httpretty.git/tree/pr313.patch is a squashed version of this PR with all my suggested changes included. Other distributors may find it handy, I guess.

File: tests/functional/test_requests.py (hunk 10 above)
Comment (gabrielfalcao) [reply tests/functional/test_requests.py]: I think it might be time to drop python 2.6 support, thoughts?

Comment (AdamWill) [reply tests/functional/test_requests.py]: I think we're still building for RHEL 6 (for the EPEL repository, which is basically Fedora packages built for RHEL), which is Python 2.6. https://koji.fedoraproject.org/koji/buildinfo?buildID=836707 is the build I did around the time I was poking this.

File: httpretty/core.py (hunk 7 above)
Comment (gabrielfalcao) [reply httpretty/core.py]: Agreed, py2.6 should not block this security update
