### ISSUE TITLE
 ssl.SSLContext.wrap_socket starting with 0.9.5 under python 2.7.8

### ISSUE THREAD

**Issue by gillesdouaire** [gabrielfalcao/HTTPretty#340]
httpretty is breaking with the latest release 0.9.5 under python 2.7.8. Unfortunately, no release notes or changelog are published.

...py27-unittest\lib\site-packages\httpretty\core.py", line 102, in <module>
   old_sslcontext_wrap_socket = ssl.SSLContext.wrap_socket
AttributeError: 'module' object has no attribute 'SSLContext

Can you guys publish some release notes so we know if this is expected or... what is the nature and goals of this change?

**Comment by macisamuele** [comment]
The same error happens on python 2.7.14: https://travis-ci.org/macisamuele/bravado/jobs/389799210

**Comment by sjaensch** [comment]
Looks like this error is caused by #339. ``ssl.SSLContext`` was [introduced with Python 2.7.9](https://docs.python.org/2/library/ssl.html#ssl-contexts), so that explains why you're seeing an exception being thrown on Python 2.7.8. On the other hand, it's not clear to me why it's failing for bravado with Python 2.7.14.

Side note: I think this issue is mainly about the error, so I'd set the title accordingly. People hitting the same error might not find this issue otherwise.

**Comment by gillesdouaire** [comment]
Hello! OK, changed the title.

**Comment by andy-maier** [comment]
Does anyone know what the reason is for this coming up on a Python version such as 2.7.14 (see @macisamuele, above) ?

We have also seen this on 2.7.14 but no Travis log available (our issue https://github.com/pywbem/pywbem/issues/1303)

**Comment by moble** [comment]
@andy-maier   At least judging from the travis log that @macisamuele pointed to, the problem really is just the use of a python version older than 2.7.9 — it's just deceptive because [tox chooses an older python executable (2.7.6)](https://travis-ci.org/macisamuele/bravado/jobs/389799210#L496) despite the fact that [travis initially claims to be using 2.7.14](https://travis-ci.org/macisamuele/bravado/jobs/389799210#L424).  

This issue is fixed even for versions older than 2.7.9 by #341.  Now we just have to wait for the next release for that to percolate down to tests that people run.
